image:
  file: .gitpod.Dockerfile

tasks:
  - name: Starting Projects
    init: composer create-project laravel/laravel:^8.0 laravel &&
      mkdir -p laravel/packages/skijasi/commerce-theme && 
      mv {,.}* laravel/packages/skijasi/commerce-theme 2>/dev/null; true &&
      cd laravel/packages/skijasi &&
      git clone --branch main --single-branch https://github.com/nadzorservera-croatia/skijasi-commerce-module.git commerce-module &&
      git clone --branch 2.x --single-branch https://github.com/nadzorservera-croatia/skijasi.git core &&
      cd ../../ &&
      cp packages/skijasi/commerce-theme/.gitpod/AppServiceProvider.php app/Providers/AppServiceProvider.php &&
      cp packages/skijasi/commerce-theme/.gitpod/app.php config/app.php &&
      cp packages/skijasi/commerce-theme/.gitpod/composer.json composer.json &&
      cp packages/skijasi/commerce-theme/.gitpod/webpack.mix.js webpack.mix.js &&
      cp packages/skijasi/commerce-theme/.gitpod/tailwind.config.js tailwind.config.js &&
      cp packages/skijasi/commerce-theme/.gitpod/skijasi-commerce.php config &&
      cp .env.example .env &&
      composer update &&
      php artisan key:generate &&
      mysql -u root -e "create database laravel"
    command: php artisan skijasi:setup --force &&
      php artisan skijasi-commerce:setup &&
      php artisan skijasi-commerce-theme:setup &&
      sed -i 's/http:\/\/localhost//g' .env &&
      sed -i 's/FILESYSTEM_DRIVER=local/FILESYSTEM_DRIVER=public/g' .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      sed -i 's/MIX_DEFAULT_MENU=general/MIX_DEFAULT_MENU=general/g' .env &&
      sed -i 's/MIX_COMMERCE_WEB_ROUTE_PREFIX=/MIX_COMMERCE_WEB_ROUTE_PREFIX=commerce/g' .env &&
      sed -i 's/MIX_SKIJASI_MENU=${MIX_DEFAULT_MENU}/MIX_SKIJASI_MENU=${MIX_DEFAULT_MENU},commerce-module,commerce-theme/g' .env &&
      echo -e "\nMIX_SKIJASI_MODULES=commerce-module,commerce-theme" >> .env &&
      echo -e "\nCOMMERCE_PRODUCTS_LIMIT_QUERY=10" >> .env &&
      echo -e "\nMIX_PAYMENT_MODULE=commerce-module" >> .env &&
      php artisan migrate &&
      php artisan db:seed --class="Database\Seeders\Skijasi\SkijasiSeeder" &&
      php artisan db:seed --class="Database\Seeders\Skijasi\Commerce\SkijasiCommerceModuleSeeder" &&
      php artisan db:seed --class="Database\Seeders\Skijasi\SkijasiSeeder" &&
      php artisan db:seed --class="Database\Seeders\Skijasi\Commerce\Theme\SkijasiCommerceThemeSeeder" &&
      php artisan storage:link &&
      php artisan migrate &&
      npm install &&
      php artisan skijasi:admin admin@admin.com --name=admin --username=admin --password=admin --confirm_password=admin --create && 
      npm run dev &&
      php artisan serve --host=0.0.0.0
ports:
  - port: 8000
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - junstyle.php-cs-fixer
    - PKief.material-icon-theme